name = "astro-strapi-blog"
main = "./dist/_worker.js"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "astro-strapi-blog-db"
database_id = "3d5ff80c-fa04-4505-9fdb-403f54161c37"
preview_database_id = "DB"
migrations_dir="drizzle"